# Generated by Django 3.1.7 on 2021-04-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_movies', '0002_auto_20210418_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contents', models.TextField()),
                ('Image', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.TextField(),
        ),
    ]
